### ISSUE TITLE
Add MAINTAINERS.md file

### ISSUE THREAD

**Issue by joewxboy** [open-horizon-services/service-edgex-foundry#1]
Please duplicate the file in https://raw.githubusercontent.com/open-horizon-services/web-helloworld-cpp/ac403917069c896f685a317f4ca6b503694f5187/MAINTAINERS.md in this repo.

**Comment by leec94** [comment]
hi, i'd like to work on this too!

**Comment by johnwalicki** [comment]
@leec94 - Caroline - I've assigned this issue to you.  Remember to sign your commit and follow the contribution guidelines.  Thanks for contributing to Open Horizon !

**Comment by leec94** [comment]
Great! I added a PR let me know if it looks okay. Thanks!

**Comment by johnwalicki** [comment]
Fixed by #2
